[DATABASE]
DIALECT = "mssql+pyodbc://"
SERVER = "DESKTOP-ERMN8SE"
INSTANCE = "INSTANCESKV"
PORT = "1433"
DB_NAME = "finance"
USER = "sa"
PASSWORD = "Mechanical"
DRIVER = "SQL+Server+Native+Client+11.0"
CONNECTION_MAX = 5000
ENABLED = "True"
AUTOCOMMIT = "True"
FAST_EXECUTE = "True"



[TELEGRAM]
BASE_URL = "https://api.telegram.org/bot"
BOT_TOKEN = ""
BOT_CHATID = ""
DISABLE_NOTIFICATION = "True"

[theme]
primaryColor="#d33682"
backgroundColor="#002b36"
secondaryBackgroundColor="#586e75"
textColor="#fafafa"
font="sans serif"
