version: "3.7"

services:
    app:
        image: robovish/streamlit:0.2
        ports:
            - 8501:8501
        working_dir: /app

    mysql:
        image: mysql:5.7
        volumes:
            - streamlit-mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: streamlit
        ports:
            - 3306:3306
    
volumes:
    streamlit-mysql-data: